### ISSUE TITLE
Error: creating EKS Access Entry 

### ISSUE THREAD

**Issue by yashodhah** [aws-samples/eks-blueprints-for-terraform-workshop#10]
When I tried to create the eks cluster I've encountered the following error.

module.eks.aws_eks_addon.this["eks-pod-identity-agent"]: Still creating... [10s elapsed]
module.eks.aws_eks_addon.this["eks-pod-identity-agent"]: Still creating... [20s elapsed]
module.eks.aws_eks_addon.this["eks-pod-identity-agent"]: Still creating... [30s elapsed]
module.eks.aws_eks_addon.this["eks-pod-identity-agent"]: Still creating... [40s elapsed]
module.eks.aws_eks_addon.this["eks-pod-identity-agent"]: Creation complete after 46s [id=hub-cluster:eks-pod-identity-agent]

Error: creating EKS Access Entry (hub-cluster:arn:aws:iam::xxxxxxxxx:role/aws-reserved/sso.amazonaws.com/ap-southeast-1/AWSReservedSSO_xxxxxxx_xxxxxxx): operation error EKS: CreateAccessEntry, https response error StatusCode: 409, RequestID: 0325e99b-78db-4ad1-8db9-a3b772640503, ResourceInUseException: The specified access entry resource is already in use on this cluster.
│ 
│   with module.eks.aws_eks_access_entry.this["eks_admin"],
│   on .terraform/modules/eks/main.tf line 191, in resource "aws_eks_access_entry" "this":
│  191: resource "aws_eks_access_entry" "this" {
│ 

I'm not using a cloud 9 instance as suggested in the workshop. Instead I'm using AWSReservedSSO_AdministratorAccess_xxxxxx role...

**Comment by yashodhah** [comment]
with cloud9 instance everything is working fine.

**Comment by allamand** [comment]
Thanks for testing this, it seems the entry was already exists.
